apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-health-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "k8s-health-service.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "k8s-health-service.name" . }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "k8s-health-service.name" . }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: APP_NAME
              value: {{ .Values.env.APP_NAME | quote }}
            - name: APP_VERSION
              value: {{ .Values.env.APP_VERSION | quote }}
            - name: CHECK_TIMEOUT_SECONDS
              value: {{ .Values.env.CHECK_TIMEOUT_SECONDS | quote }}
            - name: HTTP_CHECKS
              value: {{ .Values.env.HTTP_CHECKS | quote }}
            - name: TCP_CHECKS
              value: {{ .Values.env.TCP_CHECKS | quote }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          startupProbe:
            httpGet:
              path: /startupz
              port: http
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
