apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "k8s-health-service.fullname" . }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "k8s-health-service.name" . }}
